---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: restrictred-cluster-role
  namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: restrictred-cluster-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: restrictred-cluster-role
  namespace: kube-system

---
apiVersion: v1
kind: Pod
metadata:
  name: test
  namespace: kube-system
spec:
  serviceAccountName: restrictred-cluster-role
  containers:
  - image: bitnami/kubectl:1.23.5-debian-10-r18
    name: test
    command: ["/bin/sh"]
    args: ["-c", "sleep 3600;"]
